version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    ports:
      - '8080:8080'
      - '50051:50051'
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  gcloud-storage-emulator:
    image: fsouza/fake-gcs-server:latest
    ports:
      - 4443:4443
    command: -scheme http -public-host ${URL:-localhost}:4443 -data /data
    volumes:
      - ./gcs_fixtures:/data
      - ./gcs:/storage

volumes:
  weaviate_data:
  gcs_fixtures:
